# Recommended batch_size: 32
# Recommended learning_rate: 0.0001
# Recommended number of steps: 40000
trainingInput:
  scaleTier: CUSTOM
  # Configures a single worker with 2 NVIDIA T4 GPUs
  masterType: n1-highcpu-32
  masterConfig:
    acceleratorConfig:
      count: 2
      type: NVIDIA_TESLA_T4
  useChiefInTfConfig: True
