trainingInput:
  scaleTier: CUSTOM
  # Configure a master worker with 1 T4 GPUs
  masterType: n1-highcpu-32
  masterConfig:
    acceleratorConfig:
      count: 4
      type: nvidia-tesla-t4
  useChiefInTfConfig: True